name: Firebase Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get Firebase service account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase/firebaseServiceAccount.json

      - name: Install Dependencies
        working-directory: functions
        run: npm install

      - name: Deploy Firebase Functions
        working-directory: functions
        run: |
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
